package io.github.areswjd.piggybank.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import io.github.areswjd.piggybank.model.AppDesign

/** 테마 하나를 이루는 색·글꼴·모양·화면 장식. [forceDark]이면 폰 설정과 상관없이 항상 어두운 색을 쓴다. */
internal class DesignSpec(
    val light: ColorScheme,
    val dark: ColorScheme,
    val lightExtras: PiggyColors,
    val darkExtras: PiggyColors,
    val typography: Typography,
    val shapes: Shapes,
    val style: PiggyStyle,
    val forceDark: Boolean = false,
)

internal fun AppDesign.spec(): DesignSpec = when (this) {
    AppDesign.STRAWBERRY -> Strawberry
    AppDesign.MINT -> Mint
    AppDesign.BUTTER -> Butter
    AppDesign.LAVENDER -> Lavender
    AppDesign.SKY -> Sky
    AppDesign.PEACH -> Peach
    AppDesign.MATCHA -> Matcha
    AppDesign.NIGHT -> Night
}

private fun shapes(small: Int, medium: Int, large: Int) = Shapes(
    extraSmall = RoundedCornerShape(8.dp),
    small = RoundedCornerShape(small.dp),
    medium = RoundedCornerShape(medium.dp),
    large = RoundedCornerShape(large.dp),
    extraLarge = RoundedCornerShape(36.dp),
)

// ── A. 딸기우유 (기본): 파스텔 분홍 + 민트, 크림 배경, Jua ────────────────────────
private val Strawberry = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFFC44D75),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD6E2),
        onPrimaryContainer = Color(0xFF5A1830),
        secondary = Color(0xFF3F7F70),
        secondaryContainer = Color(0xFFCFF1E6),
        onSecondaryContainer = Color(0xFF0F3D33),
        tertiary = Color(0xFF7D6200),
        tertiaryContainer = Color(0xFFFFEDB8),
        onTertiaryContainer = Color(0xFF4A3600),
        background = Color(0xFFFFF8F4),
        onBackground = Color(0xFF3B2A30),
        surface = Color(0xFFFFF8F4),
        onSurface = Color(0xFF3B2A30),
        surfaceVariant = Color(0xFFF7E4E9),
        onSurfaceVariant = Color(0xFF7A6168),
        outline = Color(0xFFD3B9C1),
        outlineVariant = Color(0xFFF0DDE3),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF3F5),
        surfaceContainer = Color(0xFFFFEEF2),
        surfaceContainerHigh = Color(0xFFFFE8EE),
        surfaceContainerHighest = Color(0xFFFCE1E8),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFFB0C8),
        onPrimary = Color(0xFF5E1131),
        primaryContainer = Color(0xFF7D2A47),
        onPrimaryContainer = Color(0xFFFFD9E3),
        secondary = Color(0xFFA6E3D1),
        secondaryContainer = Color(0xFF24584B),
        onSecondaryContainer = Color(0xFFCFF1E6),
        tertiary = Color(0xFFF2D27A),
        tertiaryContainer = Color(0xFF5C4800),
        onTertiaryContainer = Color(0xFFFFEDB8),
        background = Color(0xFF1F1A1C),
        onBackground = Color(0xFFF2E3E7),
        surface = Color(0xFF1F1A1C),
        onSurface = Color(0xFFF2E3E7),
        surfaceVariant = Color(0xFF4A3D42),
        onSurfaceVariant = Color(0xFFD5C0C6),
        outline = Color(0xFF9E8A90),
        outlineVariant = Color(0xFF4A3D42),
        surfaceContainerLowest = Color(0xFF1A1517),
        surfaceContainerLow = Color(0xFF261F22),
        surfaceContainer = Color(0xFF2B2326),
        surfaceContainerHigh = Color(0xFF342B2F),
        surfaceContainerHighest = Color(0xFF3A3034),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2B6FD1), expense = Color(0xFFCC3D66), transfer = Color(0xFF7A7275)),
    darkExtras = PiggyColors(income = Color(0xFF8FBBFF), expense = Color(0xFFFF9DB5), transfer = Color(0xFFBDB5B8)),
    typography = StrawberryTypography,
    shapes = shapes(small = 12, medium = 20, large = 28),
    style = PiggyStyle(
        cardBorder = null,
        cardElevation = 1.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.SQUARE,
        amountHero = false,
        highlightCard = HighlightStyle.CONTAINER,
    ),
)

// ── B. 민트 사탕: 민트 + 흰 카드 테두리, 고운돋움 ───────────────────────────────
private val Mint = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFF267767),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD3F2E8),
        onPrimaryContainer = Color(0xFF0F3D33),
        secondary = Color(0xFF4A6660),
        secondaryContainer = Color(0xFFD3F2E8),
        onSecondaryContainer = Color(0xFF0F3D33),
        tertiary = Color(0xFF8A5A00),
        tertiaryContainer = Color(0xFFFFE1B0),
        onTertiaryContainer = Color(0xFF2E1D00),
        background = Color(0xFFF3FAF7),
        onBackground = Color(0xFF1F3B35),
        surface = Color(0xFFF3FAF7),
        onSurface = Color(0xFF1F3B35),
        surfaceVariant = Color(0xFFE1F3EC),
        onSurfaceVariant = Color(0xFF5A746D),
        outline = Color(0xFF9CCFC1),
        outlineVariant = Color(0xFFD9EEE7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF8FCFA),
        surfaceContainer = Color(0xFFE9F6F1),
        surfaceContainerHigh = Color(0xFFE1F3EC),
        surfaceContainerHighest = Color(0xFFD8EEE6),
    ),
    dark = darkColorScheme(
        primary = Color(0xFF7FD3BE),
        onPrimary = Color(0xFF00382D),
        primaryContainer = Color(0xFF1E5A4E),
        onPrimaryContainer = Color(0xFFB8F0DE),
        secondary = Color(0xFFB2CCC5),
        secondaryContainer = Color(0xFF2A4A43),
        onSecondaryContainer = Color(0xFFCFEDE3),
        tertiary = Color(0xFFF0C070),
        tertiaryContainer = Color(0xFF5A3D00),
        onTertiaryContainer = Color(0xFFFFE1B0),
        background = Color(0xFF101C19),
        onBackground = Color(0xFFDCEDE7),
        surface = Color(0xFF101C19),
        onSurface = Color(0xFFDCEDE7),
        surfaceVariant = Color(0xFF26332F),
        onSurfaceVariant = Color(0xFFA9C4BC),
        outline = Color(0xFF6E8C84),
        outlineVariant = Color(0xFF2E403B),
        surfaceContainerLowest = Color(0xFF0B1513),
        surfaceContainerLow = Color(0xFF15221F),
        surfaceContainer = Color(0xFF192824),
        surfaceContainerHigh = Color(0xFF20302C),
        surfaceContainerHighest = Color(0xFF283934),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2F6FCC), expense = Color(0xFFC9473C), transfer = Color(0xFF6F7B78)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFF9C90), transfer = Color(0xFFAEBBB7)),
    typography = MintTypography,
    shapes = shapes(small = 12, medium = 18, large = 22),
    style = PiggyStyle(
        cardBorder = CardBorder(width = 1.5.dp, light = Color(0xFFD9EEE7), dark = Color(0xFF2E403B), dashed = false),
        cardElevation = 0.dp,
        summaryCompact = true,
        badge = BadgeStyle.ROUNDED_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.EXTENDED,
        amountHero = true,
        highlightCard = HighlightStyle.FILLED,
    ),
)

// ── C. 버터 다이어리: 버터 노랑 + 갈색, 점선 카드, 개구 손글씨 ────────────────────
private val Butter = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFFB85A18),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFE7B8),
        onPrimaryContainer = Color(0xFF4A2A08),
        secondary = Color(0xFF7A6450),
        secondaryContainer = Color(0xFFFFE7B8),
        onSecondaryContainer = Color(0xFF4A3828),
        tertiary = Color(0xFF7A5A00),
        tertiaryContainer = Color(0xFFFFE7B8),
        onTertiaryContainer = Color(0xFF3A2800),
        background = Color(0xFFFFF6DC),
        onBackground = Color(0xFF4A3828),
        surface = Color(0xFFFFF6DC),
        onSurface = Color(0xFF4A3828),
        surfaceVariant = Color(0xFFFFEFC8),
        onSurfaceVariant = Color(0xFF7A6450),
        outline = Color(0xFFD9A867),
        outlineVariant = Color(0xFFF2E4BE),
        surfaceContainerLowest = Color(0xFFFFFDF6),
        surfaceContainerLow = Color(0xFFFFF9E8),
        surfaceContainer = Color(0xFFFFEFC8),
        surfaceContainerHigh = Color(0xFFFFE9BC),
        surfaceContainerHighest = Color(0xFFFFE2AC),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFF2A66A),
        onPrimary = Color(0xFF4A2400),
        primaryContainer = Color(0xFF6B3A10),
        onPrimaryContainer = Color(0xFFFFDCC0),
        secondary = Color(0xFFD8C2A6),
        secondaryContainer = Color(0xFF4A3A26),
        onSecondaryContainer = Color(0xFFF6E3C8),
        tertiary = Color(0xFFE8C46A),
        tertiaryContainer = Color(0xFF4A3A26),
        onTertiaryContainer = Color(0xFFF6E3C8),
        background = Color(0xFF1F1A12),
        onBackground = Color(0xFFF1E4CF),
        surface = Color(0xFF1F1A12),
        onSurface = Color(0xFFF1E4CF),
        surfaceVariant = Color(0xFF3A3122),
        onSurfaceVariant = Color(0xFFD2BFA2),
        outline = Color(0xFF9C876A),
        outlineVariant = Color(0xFF4A3E2C),
        surfaceContainerLowest = Color(0xFF19140D),
        surfaceContainerLow = Color(0xFF241E15),
        surfaceContainer = Color(0xFF2A2318),
        surfaceContainerHigh = Color(0xFF332B1E),
        surfaceContainerHighest = Color(0xFF3C3324),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2E6BB8), expense = Color(0xFFC2402F), transfer = Color(0xFF7A6A5A)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFF9E8E), transfer = Color(0xFFCBB9A3)),
    typography = ButterTypography,
    shapes = shapes(small = 10, medium = 14, large = 18),
    style = PiggyStyle(
        cardBorder = CardBorder(width = 1.5.dp, light = Color(0xFFE2C98F), dark = Color(0xFF6B5A40), dashed = true),
        cardElevation = 0.dp,
        summaryCompact = false,
        badge = BadgeStyle.STAMP,
        dayHeaderSticker = true,
        fab = FabStyle.CIRCLE_PENCIL,
        amountHero = false,
        highlightCard = HighlightStyle.OUTLINED,
    ),
)

// ── D. 라벤더 꿈: 연보라 + 분홍 포인트, Jua 제목 + 고운돋움 본문 ────────────────────────
private val Lavender = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFF7B5CC4),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE9E0FF),
        onPrimaryContainer = Color(0xFF2E1A66),
        secondary = Color(0xFFB0476F),
        secondaryContainer = Color(0xFFFFDDEB),
        onSecondaryContainer = Color(0xFF5A1830),
        tertiary = Color(0xFF7D6200),
        tertiaryContainer = Color(0xFFFFEDB8),
        onTertiaryContainer = Color(0xFF4A3600),
        background = Color(0xFFF7F4FF),
        onBackground = Color(0xFF2F2A45),
        surface = Color(0xFFF7F4FF),
        onSurface = Color(0xFF2F2A45),
        surfaceVariant = Color(0xFFECE6FA),
        onSurfaceVariant = Color(0xFF6E6890),
        outline = Color(0xFFC3B8E0),
        outlineVariant = Color(0xFFECE6FA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFBF9FF),
        surfaceContainer = Color(0xFFEFEAFF),
        surfaceContainerHigh = Color(0xFFEAE3FF),
        surfaceContainerHighest = Color(0xFFE4DCFF),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFCDBDFF),
        onPrimary = Color(0xFF33206E),
        primaryContainer = Color(0xFF4E3A94),
        onPrimaryContainer = Color(0xFFE9E0FF),
        secondary = Color(0xFFFFB0C8),
        secondaryContainer = Color(0xFF6B2A47),
        onSecondaryContainer = Color(0xFFFFD9E3),
        tertiary = Color(0xFFF2D27A),
        tertiaryContainer = Color(0xFF5C4800),
        onTertiaryContainer = Color(0xFFFFEDB8),
        background = Color(0xFF1A1824),
        onBackground = Color(0xFFE8E3F5),
        surface = Color(0xFF1A1824),
        onSurface = Color(0xFFE8E3F5),
        surfaceVariant = Color(0xFF47435A),
        onSurfaceVariant = Color(0xFFCAC3DE),
        outline = Color(0xFF938DA8),
        outlineVariant = Color(0xFF47435A),
        surfaceContainerLowest = Color(0xFF15131E),
        surfaceContainerLow = Color(0xFF221F2E),
        surfaceContainer = Color(0xFF262333),
        surfaceContainerHigh = Color(0xFF2F2B3E),
        surfaceContainerHighest = Color(0xFF383448),
    ),
    lightExtras = PiggyColors(income = Color(0xFF3A6FD8), expense = Color(0xFFCC4475), transfer = Color(0xFF7C7790)),
    darkExtras = PiggyColors(income = Color(0xFF9DBBFF), expense = Color(0xFFFF9DBA), transfer = Color(0xFFBDB8D2)),
    typography = JuaGowunTypography,
    shapes = shapes(small = 12, medium = 20, large = 24),
    style = PiggyStyle(
        cardBorder = null,
        cardElevation = 1.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.SQUARE,
        amountHero = false,
        highlightCard = HighlightStyle.CONTAINER,
    ),
)

// ── E. 하늘 구름: 하늘색 + 해님 노랑, 하늘색 테두리 카드, 고운돋움 ────────────────────────
private val Sky = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFF2F6FB8),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD6E6F8),
        onPrimaryContainer = Color(0xFF0E2F55),
        secondary = Color(0xFF7D6400),
        secondaryContainer = Color(0xFFFFF1B8),
        onSecondaryContainer = Color(0xFF4A3A00),
        tertiary = Color(0xFF3F7F70),
        tertiaryContainer = Color(0xFFCFF1E6),
        onTertiaryContainer = Color(0xFF0F3D33),
        background = Color(0xFFF2F8FF),
        onBackground = Color(0xFF1E2F45),
        surface = Color(0xFFF2F8FF),
        onSurface = Color(0xFF1E2F45),
        surfaceVariant = Color(0xFFE3EDF8),
        onSurfaceVariant = Color(0xFF5C708A),
        outline = Color(0xFFA9C3E0),
        outlineVariant = Color(0xFFD6E6F8),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7FBFF),
        surfaceContainer = Color(0xFFE6F0FC),
        surfaceContainerHigh = Color(0xFFDEEAF9),
        surfaceContainerHighest = Color(0xFFD6E4F6),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFA6C8FF),
        onPrimary = Color(0xFF00315F),
        primaryContainer = Color(0xFF1F4F86),
        onPrimaryContainer = Color(0xFFD6E6F8),
        secondary = Color(0xFFF2D27A),
        secondaryContainer = Color(0xFF5C4800),
        onSecondaryContainer = Color(0xFFFFF1B8),
        tertiary = Color(0xFFA6E3D1),
        tertiaryContainer = Color(0xFF24584B),
        onTertiaryContainer = Color(0xFFCFF1E6),
        background = Color(0xFF10161F),
        onBackground = Color(0xFFDEE6F2),
        surface = Color(0xFF10161F),
        onSurface = Color(0xFFDEE6F2),
        surfaceVariant = Color(0xFF39465A),
        onSurfaceVariant = Color(0xFFB8C6DA),
        outline = Color(0xFF8291A6),
        outlineVariant = Color(0xFF2F3B4D),
        surfaceContainerLowest = Color(0xFF0B1018),
        surfaceContainerLow = Color(0xFF171E29),
        surfaceContainer = Color(0xFF1B232F),
        surfaceContainerHigh = Color(0xFF232C3A),
        surfaceContainerHighest = Color(0xFF2B3544),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2B63C6), expense = Color(0xFFCC4466), transfer = Color(0xFF6F7B8A)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFF9DB5), transfer = Color(0xFFB3BECC)),
    typography = MintTypography,
    shapes = shapes(small = 12, medium = 20, large = 26),
    style = PiggyStyle(
        cardBorder = CardBorder(width = 1.dp, light = Color(0xFFD6E6F8), dark = Color(0xFF2F3B4D), dashed = false),
        cardElevation = 0.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.SQUARE,
        amountHero = false,
        highlightCard = HighlightStyle.FILLED,
    ),
)

// ── F. 복숭아 젤리: 복숭아 + 연두 포인트, 아주 둥근 카드, Jua ────────────────────────
private val Peach = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFFC9573C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDBCF),
        onPrimaryContainer = Color(0xFF4A1608),
        secondary = Color(0xFF3F7F5A),
        secondaryContainer = Color(0xFFDDF2E0),
        onSecondaryContainer = Color(0xFF103D22),
        tertiary = Color(0xFF7D6200),
        tertiaryContainer = Color(0xFFFFEDB8),
        onTertiaryContainer = Color(0xFF4A3600),
        background = Color(0xFFFFF5EF),
        onBackground = Color(0xFF3E2620),
        surface = Color(0xFFFFF5EF),
        onSurface = Color(0xFF3E2620),
        surfaceVariant = Color(0xFFF8E6DE),
        onSurfaceVariant = Color(0xFF866860),
        outline = Color(0xFFDDB8AA),
        outlineVariant = Color(0xFFF8E6DE),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF9F6),
        surfaceContainer = Color(0xFFFFEDE4),
        surfaceContainerHigh = Color(0xFFFFE6DA),
        surfaceContainerHighest = Color(0xFFFDDFD1),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFFB59F),
        onPrimary = Color(0xFF5F1A06),
        primaryContainer = Color(0xFF7F2E1A),
        onPrimaryContainer = Color(0xFFFFDBCF),
        secondary = Color(0xFFA8DDB5),
        secondaryContainer = Color(0xFF25553A),
        onSecondaryContainer = Color(0xFFDDF2E0),
        tertiary = Color(0xFFF2D27A),
        tertiaryContainer = Color(0xFF5C4800),
        onTertiaryContainer = Color(0xFFFFEDB8),
        background = Color(0xFF1F1916),
        onBackground = Color(0xFFF3E2DB),
        surface = Color(0xFF1F1916),
        onSurface = Color(0xFFF3E2DB),
        surfaceVariant = Color(0xFF4C3F3A),
        onSurfaceVariant = Color(0xFFD7C2BA),
        outline = Color(0xFFA08D85),
        outlineVariant = Color(0xFF4C3F3A),
        surfaceContainerLowest = Color(0xFF1A1411),
        surfaceContainerLow = Color(0xFF28201C),
        surfaceContainer = Color(0xFF2D2420),
        surfaceContainerHigh = Color(0xFF362C27),
        surfaceContainerHighest = Color(0xFF3F342F),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2E6BC8), expense = Color(0xFFD0435F), transfer = Color(0xFF857571)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFFA0A8), transfer = Color(0xFFC9B8B2)),
    typography = StrawberryTypography,
    shapes = shapes(small = 14, medium = 22, large = 30),
    style = PiggyStyle(
        cardBorder = null,
        cardElevation = 1.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.CIRCLE,
        amountHero = false,
        highlightCard = HighlightStyle.CONTAINER,
    ),
)

// ── G. 말차 라떼: 차분한 초록 + 라떼색, 베이지 테두리 카드, 개구 손글씨 제목 ────────────────────────
private val Matcha = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFF5F7F3A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDCE8C4),
        onPrimaryContainer = Color(0xFF1E300A),
        secondary = Color(0xFF7A6A50),
        secondaryContainer = Color(0xFFE4E9CF),
        onSecondaryContainer = Color(0xFF2E3222),
        tertiary = Color(0xFF8A5A00),
        tertiaryContainer = Color(0xFFFFE1B0),
        onTertiaryContainer = Color(0xFF2E1D00),
        background = Color(0xFFF6F3EA),
        onBackground = Color(0xFF2E3222),
        surface = Color(0xFFF6F3EA),
        onSurface = Color(0xFF2E3222),
        surfaceVariant = Color(0xFFECE8D9),
        onSurfaceVariant = Color(0xFF6E705C),
        outline = Color(0xFFC9C2AA),
        outlineVariant = Color(0xFFEAE4D2),
        surfaceContainerLowest = Color(0xFFFFFDF7),
        surfaceContainerLow = Color(0xFFFAF8F1),
        surfaceContainer = Color(0xFFEEEADC),
        surfaceContainerHigh = Color(0xFFE8E4D4),
        surfaceContainerHighest = Color(0xFFE2DDCB),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFB6D18F),
        onPrimary = Color(0xFF243A0A),
        primaryContainer = Color(0xFF3F5A20),
        onPrimaryContainer = Color(0xFFDCE8C4),
        secondary = Color(0xFFD2C6AE),
        secondaryContainer = Color(0xFF4A4232),
        onSecondaryContainer = Color(0xFFEEE6D2),
        tertiary = Color(0xFFF0C070),
        tertiaryContainer = Color(0xFF5A3D00),
        onTertiaryContainer = Color(0xFFFFE1B0),
        background = Color(0xFF181A13),
        onBackground = Color(0xFFE5E3D7),
        surface = Color(0xFF181A13),
        onSurface = Color(0xFFE5E3D7),
        surfaceVariant = Color(0xFF45473A),
        onSurfaceVariant = Color(0xFFC6C6B2),
        outline = Color(0xFF909080),
        outlineVariant = Color(0xFF3A3C30),
        surfaceContainerLowest = Color(0xFF13150F),
        surfaceContainerLow = Color(0xFF20221A),
        surfaceContainer = Color(0xFF24261E),
        surfaceContainerHigh = Color(0xFF2D2F26),
        surfaceContainerHighest = Color(0xFF36382E),
    ),
    lightExtras = PiggyColors(income = Color(0xFF3566B0), expense = Color(0xFFC24A3A), transfer = Color(0xFF7A7666)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFF9E8E), transfer = Color(0xFFC4C0AE)),
    typography = ButterTypography,
    shapes = shapes(small = 10, medium = 14, large = 16),
    style = PiggyStyle(
        cardBorder = CardBorder(width = 1.dp, light = Color(0xFFDDD6C2), dark = Color(0xFF4A4636), dashed = false),
        cardElevation = 0.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.SQUARE,
        amountHero = false,
        highlightCard = HighlightStyle.OUTLINED,
    ),
)

// H는 밝은 모드에서도 같은 어두운 색을 쓴다. Night보다 먼저 선언해야 초기화 순서가 맞는다.
private val NightScheme = darkColorScheme(
    primary = Color(0xFFFFD36E),
    onPrimary = Color(0xFF3A2A00),
    primaryContainer = Color(0xFF5A4A10),
    onPrimaryContainer = Color(0xFFFFE9A8),
    secondary = Color(0xFFC9C4F0),
    secondaryContainer = Color(0xFF3A3F70),
    onSecondaryContainer = Color(0xFFEDEBFF),
    tertiary = Color(0xFFFFB3CF),
    tertiaryContainer = Color(0xFF5A2A48),
    onTertiaryContainer = Color(0xFFFFD9E8),
    background = Color(0xFF1C1F3A),
    onBackground = Color(0xFFEDEBFF),
    surface = Color(0xFF1C1F3A),
    onSurface = Color(0xFFEDEBFF),
    surfaceVariant = Color(0xFF343964),
    onSurfaceVariant = Color(0xFFA9A6CC),
    outline = Color(0xFF6E72A0),
    outlineVariant = Color(0xFF343964),
    surfaceContainerLowest = Color(0xFF262A4D),
    surfaceContainerLow = Color(0xFF23274A),
    surfaceContainer = Color(0xFF23274A),
    surfaceContainerHigh = Color(0xFF2E3360),
    surfaceContainerHighest = Color(0xFF383D6E),
)

// ── H. 별밤: 남색 밤하늘 + 금색 별. 폰 설정과 상관없이 항상 어두운 화면 ────────────────────────
private val Night = DesignSpec(
    light = NightScheme,
    dark = NightScheme,
    lightExtras = PiggyColors(income = Color(0xFF8FB4FF), expense = Color(0xFFFF8FB1), transfer = Color(0xFFB9B6D6)),
    darkExtras = PiggyColors(income = Color(0xFF8FB4FF), expense = Color(0xFFFF8FB1), transfer = Color(0xFFB9B6D6)),
    typography = JuaGowunTypography,
    shapes = shapes(small = 12, medium = 20, large = 24),
    style = PiggyStyle(
        cardBorder = null,
        cardElevation = 0.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.SQUARE,
        amountHero = false,
        highlightCard = HighlightStyle.FILLED,
    ),
    forceDark = true,
)
