package io.github.areswjd.piggybank.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import io.github.areswjd.piggybank.model.AppDesign

/** 디자인 하나를 이루는 색·글꼴·모양·화면 장식. */
internal class DesignSpec(
    val light: ColorScheme,
    val dark: ColorScheme,
    val lightExtras: PiggyColors,
    val darkExtras: PiggyColors,
    val typography: Typography,
    val shapes: Shapes,
    val style: PiggyStyle,
)

internal fun AppDesign.spec(): DesignSpec = when (this) {
    AppDesign.STRAWBERRY -> Strawberry
    AppDesign.MINT -> Mint
    AppDesign.BUTTER -> Butter
}

private fun shapes(small: Int, medium: Int, large: Int) = Shapes(
    extraSmall = RoundedCornerShape(8.dp),
    small = RoundedCornerShape(small.dp),
    medium = RoundedCornerShape(medium.dp),
    large = RoundedCornerShape(large.dp),
    extraLarge = RoundedCornerShape(36.dp),
)

// ── A. 딸기우유 (기본): 파스텔 분홍 + 민트, 크림 배경, Jua ────────────────────────
private val Strawberry = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFFC44D75),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD6E2),
        onPrimaryContainer = Color(0xFF5A1830),
        secondary = Color(0xFF3F7F70),
        secondaryContainer = Color(0xFFCFF1E6),
        onSecondaryContainer = Color(0xFF0F3D33),
        tertiary = Color(0xFF7D6200),
        tertiaryContainer = Color(0xFFFFEDB8),
        onTertiaryContainer = Color(0xFF4A3600),
        background = Color(0xFFFFF8F4),
        onBackground = Color(0xFF3B2A30),
        surface = Color(0xFFFFF8F4),
        onSurface = Color(0xFF3B2A30),
        surfaceVariant = Color(0xFFF7E4E9),
        onSurfaceVariant = Color(0xFF7A6168),
        outline = Color(0xFFD3B9C1),
        outlineVariant = Color(0xFFF0DDE3),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF3F5),
        surfaceContainer = Color(0xFFFFEEF2),
        surfaceContainerHigh = Color(0xFFFFE8EE),
        surfaceContainerHighest = Color(0xFFFCE1E8),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFFB0C8),
        onPrimary = Color(0xFF5E1131),
        primaryContainer = Color(0xFF7D2A47),
        onPrimaryContainer = Color(0xFFFFD9E3),
        secondary = Color(0xFFA6E3D1),
        secondaryContainer = Color(0xFF24584B),
        onSecondaryContainer = Color(0xFFCFF1E6),
        tertiary = Color(0xFFF2D27A),
        tertiaryContainer = Color(0xFF5C4800),
        onTertiaryContainer = Color(0xFFFFEDB8),
        background = Color(0xFF1F1A1C),
        onBackground = Color(0xFFF2E3E7),
        surface = Color(0xFF1F1A1C),
        onSurface = Color(0xFFF2E3E7),
        surfaceVariant = Color(0xFF4A3D42),
        onSurfaceVariant = Color(0xFFD5C0C6),
        outline = Color(0xFF9E8A90),
        outlineVariant = Color(0xFF4A3D42),
        surfaceContainerLowest = Color(0xFF1A1517),
        surfaceContainerLow = Color(0xFF261F22),
        surfaceContainer = Color(0xFF2B2326),
        surfaceContainerHigh = Color(0xFF342B2F),
        surfaceContainerHighest = Color(0xFF3A3034),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2B6FD1), expense = Color(0xFFCC3D66), transfer = Color(0xFF7A7275)),
    darkExtras = PiggyColors(income = Color(0xFF8FBBFF), expense = Color(0xFFFF9DB5), transfer = Color(0xFFBDB5B8)),
    typography = StrawberryTypography,
    shapes = shapes(small = 12, medium = 20, large = 28),
    style = PiggyStyle(
        cardBorder = null,
        cardElevation = 1.dp,
        summaryCompact = false,
        badge = BadgeStyle.CIRCLE_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.SQUARE,
        amountHero = false,
        highlightCard = HighlightStyle.CONTAINER,
    ),
)

// ── B. 민트 사탕: 민트 + 흰 카드 테두리, 고운돋움 ───────────────────────────────
private val Mint = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFF267767),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD3F2E8),
        onPrimaryContainer = Color(0xFF0F3D33),
        secondary = Color(0xFF4A6660),
        secondaryContainer = Color(0xFFD3F2E8),
        onSecondaryContainer = Color(0xFF0F3D33),
        tertiary = Color(0xFF8A5A00),
        tertiaryContainer = Color(0xFFFFE1B0),
        onTertiaryContainer = Color(0xFF2E1D00),
        background = Color(0xFFF3FAF7),
        onBackground = Color(0xFF1F3B35),
        surface = Color(0xFFF3FAF7),
        onSurface = Color(0xFF1F3B35),
        surfaceVariant = Color(0xFFE1F3EC),
        onSurfaceVariant = Color(0xFF5A746D),
        outline = Color(0xFF9CCFC1),
        outlineVariant = Color(0xFFD9EEE7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF8FCFA),
        surfaceContainer = Color(0xFFE9F6F1),
        surfaceContainerHigh = Color(0xFFE1F3EC),
        surfaceContainerHighest = Color(0xFFD8EEE6),
    ),
    dark = darkColorScheme(
        primary = Color(0xFF7FD3BE),
        onPrimary = Color(0xFF00382D),
        primaryContainer = Color(0xFF1E5A4E),
        onPrimaryContainer = Color(0xFFB8F0DE),
        secondary = Color(0xFFB2CCC5),
        secondaryContainer = Color(0xFF2A4A43),
        onSecondaryContainer = Color(0xFFCFEDE3),
        tertiary = Color(0xFFF0C070),
        tertiaryContainer = Color(0xFF5A3D00),
        onTertiaryContainer = Color(0xFFFFE1B0),
        background = Color(0xFF101C19),
        onBackground = Color(0xFFDCEDE7),
        surface = Color(0xFF101C19),
        onSurface = Color(0xFFDCEDE7),
        surfaceVariant = Color(0xFF26332F),
        onSurfaceVariant = Color(0xFFA9C4BC),
        outline = Color(0xFF6E8C84),
        outlineVariant = Color(0xFF2E403B),
        surfaceContainerLowest = Color(0xFF0B1513),
        surfaceContainerLow = Color(0xFF15221F),
        surfaceContainer = Color(0xFF192824),
        surfaceContainerHigh = Color(0xFF20302C),
        surfaceContainerHighest = Color(0xFF283934),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2F6FCC), expense = Color(0xFFC9473C), transfer = Color(0xFF6F7B78)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFF9C90), transfer = Color(0xFFAEBBB7)),
    typography = MintTypography,
    shapes = shapes(small = 12, medium = 18, large = 22),
    style = PiggyStyle(
        cardBorder = CardBorder(width = 1.5.dp, light = Color(0xFFD9EEE7), dark = Color(0xFF2E403B), dashed = false),
        cardElevation = 0.dp,
        summaryCompact = true,
        badge = BadgeStyle.ROUNDED_ICON,
        dayHeaderSticker = false,
        fab = FabStyle.EXTENDED,
        amountHero = true,
        highlightCard = HighlightStyle.FILLED,
    ),
)

// ── C. 버터 다이어리: 버터 노랑 + 갈색, 점선 카드, 개구 손글씨 ────────────────────
private val Butter = DesignSpec(
    light = lightColorScheme(
        primary = Color(0xFFB85A18),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFE7B8),
        onPrimaryContainer = Color(0xFF4A2A08),
        secondary = Color(0xFF7A6450),
        secondaryContainer = Color(0xFFFFE7B8),
        onSecondaryContainer = Color(0xFF4A3828),
        tertiary = Color(0xFF7A5A00),
        tertiaryContainer = Color(0xFFFFE7B8),
        onTertiaryContainer = Color(0xFF3A2800),
        background = Color(0xFFFFF6DC),
        onBackground = Color(0xFF4A3828),
        surface = Color(0xFFFFF6DC),
        onSurface = Color(0xFF4A3828),
        surfaceVariant = Color(0xFFFFEFC8),
        onSurfaceVariant = Color(0xFF7A6450),
        outline = Color(0xFFD9A867),
        outlineVariant = Color(0xFFF2E4BE),
        surfaceContainerLowest = Color(0xFFFFFDF6),
        surfaceContainerLow = Color(0xFFFFF9E8),
        surfaceContainer = Color(0xFFFFEFC8),
        surfaceContainerHigh = Color(0xFFFFE9BC),
        surfaceContainerHighest = Color(0xFFFFE2AC),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFF2A66A),
        onPrimary = Color(0xFF4A2400),
        primaryContainer = Color(0xFF6B3A10),
        onPrimaryContainer = Color(0xFFFFDCC0),
        secondary = Color(0xFFD8C2A6),
        secondaryContainer = Color(0xFF4A3A26),
        onSecondaryContainer = Color(0xFFF6E3C8),
        tertiary = Color(0xFFE8C46A),
        tertiaryContainer = Color(0xFF4A3A26),
        onTertiaryContainer = Color(0xFFF6E3C8),
        background = Color(0xFF1F1A12),
        onBackground = Color(0xFFF1E4CF),
        surface = Color(0xFF1F1A12),
        onSurface = Color(0xFFF1E4CF),
        surfaceVariant = Color(0xFF3A3122),
        onSurfaceVariant = Color(0xFFD2BFA2),
        outline = Color(0xFF9C876A),
        outlineVariant = Color(0xFF4A3E2C),
        surfaceContainerLowest = Color(0xFF19140D),
        surfaceContainerLow = Color(0xFF241E15),
        surfaceContainer = Color(0xFF2A2318),
        surfaceContainerHigh = Color(0xFF332B1E),
        surfaceContainerHighest = Color(0xFF3C3324),
    ),
    lightExtras = PiggyColors(income = Color(0xFF2E6BB8), expense = Color(0xFFC2402F), transfer = Color(0xFF7A6A5A)),
    darkExtras = PiggyColors(income = Color(0xFF9DC1FF), expense = Color(0xFFFF9E8E), transfer = Color(0xFFCBB9A3)),
    typography = ButterTypography,
    shapes = shapes(small = 10, medium = 14, large = 18),
    style = PiggyStyle(
        cardBorder = CardBorder(width = 1.5.dp, light = Color(0xFFE2C98F), dark = Color(0xFF6B5A40), dashed = true),
        cardElevation = 0.dp,
        summaryCompact = false,
        badge = BadgeStyle.STAMP,
        dayHeaderSticker = true,
        fab = FabStyle.CIRCLE_PENCIL,
        amountHero = false,
        highlightCard = HighlightStyle.OUTLINED,
    ),
)
